<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-O5JC87R" failures="0" tests="6" name="swaglab_test.LoginTest" time="16.299" errors="1" timestamp="2025-07-17T20:11:58 IST" skipped="5">
  <testcase classname="swaglab_test.LoginTest" name="loginSuccessTest" time="0.000">
    <skipped/>
  </testcase> <!-- loginSuccessTest -->
  <testcase classname="swaglab_test.LoginTest" name="setUp" time="16.298">
    <error message="Sheet named &#039;data&#039; not found!" type="java.lang.IllegalStateException">
      <![CDATA[java.lang.IllegalStateException: Sheet named 'data' not found!
at swaglab_test.BaseClass.setUp(BaseClass.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase classname="swaglab_test.LoginTest" name="loginFailureTest" time="0.000">
    <skipped/>
  </testcase> <!-- loginFailureTest -->
  <testcase classname="swaglab_test.LoginTest" name="lockedUserFailureTest" time="0.001">
    <skipped/>
  </testcase> <!-- lockedUserFailureTest -->
  <testcase classname="swaglab_test.LoginTest" name="loginFailureTestFromExcel" time="0.000">
    <skipped/>
  </testcase> <!-- loginFailureTestFromExcel -->
  <testcase classname="swaglab_test.LoginTest" name="loginFailureTestFromProperties" time="0.000">
    <skipped/>
  </testcase> <!-- loginFailureTestFromProperties -->
</testsuite> <!-- swaglab_test.LoginTest -->
